#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    depends_on:
       - redis
    links:
       - redis
    ports:
       - 8000:8000
    command: python /code/coderunner/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    expose:
      - 6379
